### ISSUE TITLE
 "kafka: client has run out of available brokers to talk to" with a broker that is working with command line commands

### ISSUE THREAD

**Issue by dhakerk** [Mongey/terraform-provider-kafka#196]
Hi
I have a broker running locally , without any security implemented yet this command line is working :
./kafka-topics --bootstrap-server localhost:9092 --create --topic test_topic 
Created topic test_topic.

but this is not working 
terraform {
  required_providers {
    kafka = {
      source = "Mongey/kafka"
      version = "0.3.3"
    }
  }
}

provider "kafka" {
  bootstrap_servers = ["localhost:9092"]
}

resource "kafka_topic" "logs" {
  name               = "systemd_logs"
  replication_factor = 2
  partitions         = 100

  config = {
    "segment.ms"     = "20000"
    "cleanup.policy" = "compact"
  }
}

 Error: EOF
│ kafka: client has run out of available brokers to talk to (Is your cluster reachable?)
│ 
│   with kafka_topic.logs,
│   on test.tf line 14, in resource "kafka_topic" "logs":
│   14: resource "kafka_topic" "logs" {

if I change this brocker property socket.request.max.bytes to 1073741824 the terraform apply command stuck without any response

Thanks

**Comment by dhakerk** [comment]
Hi, In the broker side I see this log 
[2021-09-10 11:08:55,963] WARN [SocketServer brokerId=0] Unexpected error from /127.0.0.1; closing connection (org.apache.kafka.common.network.Selector)
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 369295616 larger than 104857600)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:105)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:507)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:438)
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:750)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:602)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:498)
	at kafka.network.Processor.poll(SocketServer.scala:981)
	at kafka.network.Processor.run(SocketServer.scala:883)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by Mongey** [comment]
You need to disable TLS
```hcl
provider "kafka" {
  bootstrap_servers = ["localhost:9092"]
  tls_enabled       = false
}
```
