### ISSUE TITLE
[0.4.3] Unable to import kafka_topic. Cannot import non-existent remote object.

### ISSUE THREAD

**Issue by Tzrlk** [Mongey/terraform-provider-kafka#252]
Similar to #120, I previously created a bunch of topics, then removed them from the state. When attempting to re-import them, the following result was received:
```shell
> terragrunt import kafka_topic.Topics[\"TOPIC.ID\"] TOPIC.NAME
```
```
kafka_topic.Topics["TOPIC.ID"]: Importing from ID "TOPIC.NAME"...
kafka_topic.Topics["TOPIC.ID"]: Import prepared!
  Prepared kafka_topic for import
kafka_topic.Topics["TOPIC.ID"]: Refreshing state... [id=TOPIC.NAME]
╷
│ Error: Cannot import non-existent remote object
│
│ While attempting to import an existing object to
│ "kafka_topic.Topics[\"TOPIC.ID\"]", the provider detected that
│ no object exists with the given id. Only pre-existing objects can be
│ imported; check that the id is correct and that it is associated with the
│ provider's configured region or endpoint, or use "terraform apply" to
│ create a new remote object for this resource.
```
To make sure that I hadn't screwed-up escaping or something, I attempted to just create the same topic on top of the "non-existent" one:
```shell
> terragrunt apply -target kafka_topic.Topics[\"TOPIC.ID\"]
```
```
  # kafka_topic.Topics["TOPIC.ID"] will be created
  + resource "kafka_topic" "Topics" {
      + config             = {
          + "cleanup.policy"    = "delete"
          + "max.message.bytes" = "10485760"
          + "segment.ms"        = "50000"
        }
      + id                 = (known after apply)
      + name               = "TOPIC.NAME"
      + partitions         = 3
      + replication_factor = 3
    }
```
```
kafka_topic.Topics["TOPIC.ID"]: Creating...
╷
│ Error: kafka server: Topic with this name already exists.
│
│   with kafka_topic.Topics["TOPIC.ID"],
│   on topics.tf line 129, in resource "kafka_topic" "Topics":
│  129: resource "kafka_topic" "Topics" {
```
I guess it _does_ exist.

This is the provider config I'm using to connect:
```terraform
variable "ClusterName" {
	description = "The name of the kafka cluster to configure."
	type        = string
}
data "aws_msk_cluster" "Cluster" {
	cluster_name = var.ClusterName
}
variable "AdminAuth" {
	description = "The ARN of the secretsmanager secret storing the Kafka admin auth details."
	type        = string
}
data "aws_secretsmanager_secret_version" "ScramAdmin" {
	secret_id = var.AdminAuth
}
locals {
	AdminAuth = jsondecode(data.aws_secretsmanager_secret_version.ScramAdmin.secret_string)
}
provider "kafka" {
	bootstrap_servers = split(",", data.aws_msk_cluster.Cluster.bootstrap_brokers_sasl_scram)
	tls_enabled       = true
	sasl_username     = local.AdminAuth[ "username" ]
	sasl_password     = local.AdminAuth[ "password" ]
	sasl_mechanism    = "scram-sha512"
}
```

I suspect the issue may be to do with user access/auth, but I don't have a lot of options for configuring that. I'd rather be using IAM auth, but that isn't currently available, and I can't get client cert auth set up without jumping through a pile of security process hoops (as it requires a signing authority in ACM).

I believe I originally removed the topics from state because they had gotten stuck and refused to be altered/destroyed by Terraform.

**Comment by Tzrlk** [comment]
Whelp, looks like my issue was to do with ACLs. Stripping all the ACLs out and relegating SCRAM solely for admin access appears all I can feasibly do to avoid locking myself out of the cluster.

Of course after I ran some topic modifications, I got this:
```
│ Error: Plugin did not respond
│
│   with kafka_topic.Topics["TOPIC.ID"],
│   on topics.tf line 85, in resource "kafka_topic" "Topics":
│   85: resource "kafka_topic" "Topics" {
│
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
```
```
Stack trace from the terraform-provider-kafka_v0.4.3.exe plugin:

fatal error: concurrent map writes

goroutine 285 [running]:
runtime.throw(0x189ad51, 0x15)
        /opt/hostedtoolcache/go/1.16.14/x64/src/runtime/panic.go:1117 +0x79 fp=0xc00044dab0 sp=0xc00044da80 pc=0xdfb539
runtime.mapassign_faststr(0x1772780, 0xc0000894d0, 0xc000092f50, 0x50, 0xc0001702c8)
        /opt/hostedtoolcache/go/1.16.14/x64/src/runtime/map_faststr.go:211 +0x411 fp=0xc00044db18 sp=0xc00044dab0 pc=0xdd5091
github.com/Mongey/terraform-provider-kafka/kafka.(*Client).extractTopics(0xc000501f50, 0xc0001eaa70, 0x1)
        /home/runner/work/terraform-provider-kafka/terraform-provider-kafka/kafka/client.go:189 +0x147 fp=0xc00044db90 sp=0xc00044db18 pc=0x169dd87
github.com/Mongey/terraform-provider-kafka/kafka.(*Client).ReadTopic(0xc000501f50, 0xc0006caea0, 0x2b, 0xc00007e001, 0x2, 0xc0000921e0, 0x4f, 0x0, 0x0, 0x4f)
        /home/runner/work/terraform-provider-kafka/terraform-provider-kafka/kafka/client.go:488 +0x39b fp=0xc00044dcb0 sp=0xc00044db90 pc=0x16a03db
github.com/Mongey/terraform-provider-kafka/kafka.(*LazyClient).ReadTopic(0xc0005d39e0, 0xc0006caea0, 0x2b, 0x1, 0x1, 0xffffffffffffffff, 0xffffffffffffffff, 0x0, 0x0, 0x1)
        /home/runner/work/terraform-provider-kafka/terraform-provider-kafka/kafka/lazy_client.go:74 +0xbd fp=0xc00044dd10 sp=0xc00044dcb0 pc=0x16a6ffd
github.com/Mongey/terraform-provider-kafka/kafka.topicRefreshFunc.func1(0xc000773ee0, 0xc000773ea0, 0x0, 0x0, 0x2, 0x1)
        /home/runner/work/terraform-provider-kafka/terraform-provider-kafka/kafka/resource_kafka_topic.go:197 +0x12c fp=0xc00044de20 sp=0xc00044dd10 pc=0x16b27ac
github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.(*StateChangeConf).WaitForStateContext.func1(0xc000301740, 0xc000332700, 0xc0004f8900, 0xc0006a8380, 0xc000634090, 0xc000634088)
        /home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.11.0/helper/resource/state.go:110 +0x309 fp=0xc00044dfb0 sp=0xc00044de20 pc=0x1649a89
runtime.goexit()
        /opt/hostedtoolcache/go/1.16.14/x64/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc00044dfb8 sp=0xc00044dfb0 pc=0xe301a1
created by github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.(*StateChangeConf).WaitForStateContext
        /home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.11.0/helper/resource/state.go:83 +0x1d9

goroutine 1 [select]:
github.com/hashicorp/go-plugin.Serve(0xc0003001e0)
        /home/runner/go/pkg/mod/github.com/hashicorp/go-plugin@v1.4.3/server.go:469 +0x954
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.Serve(0x1890e9b, 0x8, 0xc000306140, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/tf5server/server.go:311 +0xb34
github.com/hashicorp/terraform-plugin-sdk/v2/plugin.tf5serverServe(0xc000300180, 0xc000306140, 0x1a3a360)
        /home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.11.0/plugin/serve.go:178 +0xa5
github.com/hashicorp/terraform-plugin-sdk/v2/plugin.Serve(0xc000300180)
        /home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.11.0/plugin/serve.go:118 +0x1a6
main.main()
        /home/runner/work/terraform-provider-kafka/terraform-provider-kafka/main.go:27 +0x118

goroutine 8 [select]:
github.com/hashicorp/go-plugin.(*gRPCBrokerServer).Recv(0xc000088570, 0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/github.com/hashicorp/go-plugin@v1.4.3/grpc_broker.go:121 +0x8d
github.com/hashicorp/go-plugin.(*GRPCBroker).Run(0xc0002cc0a0)
        /home/runner/go/pkg/mod/github.com/hashicorp/go-plugin@v1.4.3/grpc_broker.go:411 +0x85
created by github.com/hashicorp/go-plugin.(*GRPCServer).Init
        /home/runner/go/pkg/mod/github.com/hashicorp/go-plugin@v1.4.3/grpc_server.go:85 +0x365

goroutine 9 [syscall, locked to thread]:
syscall.Syscall6(0x7ffb1b674ee0, 0x5, 0x184, 0xc000209000, 0x1000, 0xc0000afd1c, 0x0, 0x0, 0x0, 0x0, ...)
        /opt/hostedtoolcache/go/1.16.14/x64/src/runtime/syscall_windows.go:347 +0xf2
syscall.ReadFile(0x184, 0xc000209000, 0x1000, 0x1000, 0xc0000afd1c, 0x0, 0x7ffff800000, 0x2)
        /opt/hostedtoolcache/go/1.16.14/x64/src/syscall/zsyscall_windows.go:1006 +0x105
syscall.Read(0x184, 0xc000209000, 0x1000, 0x1000, 0x0, 0x0, 0x8)
        /opt/hostedtoolcache/go/1.16.14/x64/src/syscall/syscall_windows.go:369 +0x6f
internal/poll.(*FD).Read(0xc000258500, 0xc000209000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.16.14/x64/src/internal/poll/fd_windows.go:427 +0x225
os.(*File).read(...)
        /opt/hostedtoolcache/go/1.16.14/x64/src/os/file_posix.go:31
os.(*File).Read(0xc00008e018, 0xc000209000, 0x1000, 0x1000, 0x400, 0x1737cc0, 0x1)
        /opt/hostedtoolcache/go/1.16.14/x64/src/os/file.go:117 +0x85
bufio.(*Reader).Read(0xc0000aff50, 0xc0001fe000, 0x400, 0x400, 0x0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.16.14/x64/src/bufio/bufio.go:227 +0x238
github.com/hashicorp/go-plugin.copyChan(0x1a5c168, 0xc0003d61b0, 0xc0000427e0, 0x1a3c540, 0xc00008e018)
        /home/runner/go/pkg/mod/github.com/hashicorp/go-plugin@v1.4.3/grpc_stdio.go:181 +0xd0
created by github.com/hashicorp/go-plugin.newGRPCStdioServer
        /home/runner/go/pkg/mod/github.com/hashicorp/go-plugin@v1.4.3/grpc_stdio.go:37 +0xbc

goroutine 10 [syscall, locked to thread]:
syscall.Syscall6(0x7ffb1b674ee0, 0x5, 0x1a4, 0xc000347000, 0x1000, 0xc0004b5d1c, 0x0, 0x0, 0x0, 0x0, ...)
        /opt/hostedtoolcache/go/1.16.14/x64/src/runtime/syscall_windows.go:347 +0xf2
syscall.ReadFile(0x1a4, 0xc000347000, 0x1000, 0x1000, 0xc0004b5d1c, 0x0, 0x7ffff800000, 0x2)
        /opt/hostedtoolcache/go/1.16.14/x64/src/syscall/zsyscall_windows.go:1006 +0x105
syscall.Read(0x1a4, 0xc000347000, 0x1000, 0x1000, 0xdfe245, 0xc0004b5d60, 0x8)
        /opt/hostedtoolcache/go/1.16.14/x64/src/syscall/syscall_windows.go:369 +0x6f
internal/poll.(*FD).Read(0xc000258f00, 0xc000347000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.16.14/x64/src/internal/poll/fd_windows.go:427 +0x225
os.(*File).read(...)
        /opt/hostedtoolcache/go/1.16.14/x64/src/os/file_posix.go:31
os.(*File).Read(0xc00008e030, 0xc000347000, 0x1000, 0x1000, 0x400, 0x1737cc0, 0x15f9f01)
        /opt/hostedtoolcache/go/1.16.14/x64/src/os/file.go:117 +0x85
bufio.(*Reader).Read(0xc0004b5f50, 0xc00060c000, 0x400, 0x400, 0xfe, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.16.14/x64/src/bufio/bufio.go:227 +0x238
github.com/hashicorp/go-plugin.copyChan(0x1a5c168, 0xc0003d61b0, 0xc000042840, 0x1a3c540, 0xc00008e030)
        /home/runner/go/pkg/mod/github.com/hashicorp/go-plugin@v1.4.3/grpc_stdio.go:181 +0xd0
created by github.com/hashicorp/go-plugin.newGRPCStdioServer
        /home/runner/go/pkg/mod/github.com/hashicorp/go-plugin@v1.4.3/grpc_stdio.go:38 +0x109

goroutine 11 [syscall]:
os/signal.signal_recv(0x0)
        /opt/hostedtoolcache/go/1.16.14/x64/src/runtime/sigqueue.go:168 +0xaf
os/signal.loop()
        /opt/hostedtoolcache/go/1.16.14/x64/src/os/signal/signal_unix.go:23 +0x29
created by os/signal.Notify.func1.1
        /opt/hostedtoolcache/go/1.16.14/x64/src/os/signal/signal.go:151 +0x4b

goroutine 12 [chan receive]:
github.com/hashicorp/go-plugin.Serve.func3(0xc000300300, 0x1a5c168, 0xc0003d61b0)
        /home/runner/go/pkg/mod/github.com/hashicorp/go-plugin@v1.4.3/server.go:434 +0x90
created by github.com/hashicorp/go-plugin.Serve
        /home/runner/go/pkg/mod/github.com/hashicorp/go-plugin@v1.4.3/server.go:431 +0xb94

goroutine 13 [IO wait]:
internal/poll.runtime_pollWait(0x1ecfa20b0c0, 0x72, 0x1a3d4e0)
        /opt/hostedtoolcache/go/1.16.14/x64/src/runtime/netpoll.go:227 +0x65
internal/poll.(*pollDesc).wait(0xc0003de1b8, 0x72, 0x1edf500, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.16.14/x64/src/internal/poll/fd_poll_runtime.go:87 +0x4c

Error: The terraform-provider-kafka_v0.4.3.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```
Though that's another issue altogether.
